FROM golang:1.19 AS builder

WORKDIR /build

RUN dpkg --add-architecture amd64 \
    && apt update \
    && apt-get install -y --no-install-recommends gcc-x86-64-linux-gnu libc6-dev-amd64-cross

COPY go.mod go.sum Makefile ./
RUN go mod download

COPY . ./
RUN go install github.com/go-bindata/go-bindata/go-bindata github.com/gobuffalo/packr/v2/packr2
RUN make sqlbin && packr2
RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 go build

# To compile this image manually run:
#
# $ GO111MODULE=on GOOS=linux GOARCH=amd64 go build && docker build -t oryd/hydra:v1.0.0-rc.7_oryOS.10 . && rm hydra
FROM alpine:3.17

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin
RUN apk add -U --no-cache ca-certificates

COPY --from=builder /build/hydra /usr/bin/hydra

# set up nsswitch.conf for Go's "netgo" implementation
# - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
RUN echo 'hosts: files dns' > /etc/nsswitch.conf

USER ory

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
