# Hasura hardened Alpine image for Hydra v1.4.x (self-hosted / DDN).
# Built manually and pushed to gcr.io/hasura-ee/hydra.
#
# Versioning: Hasura maintains its own patch version independent of upstream
# Ory tags. Increment the Hasura patch version each time the image is rebuilt
# (e.g. v1.4.14, v1.4.15, …). Append the Alpine version to the tag.
#
# Build & push:
#   docker build -f Dockerfile-alpine -t gcr.io/hasura-ee/hydra:v1.4.14-alpine3.23.6 .
#   docker push gcr.io/hasura-ee/hydra:v1.4.14-alpine3.23.6

FROM golang:1.26.8-bookworm@sha256:a688600ca24f8a4d3ca77f95b0dd40704a9fc787c826660eb7ba0b641b8b175d AS builder

WORKDIR /build

ENV GOTOOLCHAIN=local

RUN dpkg --add-architecture amd64 \
    && apt update \
    && apt-get install -y --no-install-recommends gcc-x86-64-linux-gnu libc6-dev-amd64-cross

COPY go.mod go.sum Makefile ./
RUN go mod download

COPY . ./
RUN go install github.com/go-bindata/go-bindata/go-bindata github.com/gobuffalo/packr/v2/packr2
RUN make sqlbin && packr2
RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 go build -trimpath

FROM alpine:3.23.6@sha256:85fe1e81d6758c208f3e1eed4338a1997e19d4be002d4dd32d3100c9a8c010a0

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin
RUN apk add -U --no-cache ca-certificates

COPY --from=builder /build/hydra /usr/bin/hydra

# set up nsswitch.conf for Go's "netgo" implementation
# - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
RUN echo 'hosts: files dns' > /etc/nsswitch.conf

USER ory

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
